### DISCUSSION TITLE
No report found

### DISCUSSION THREAD

**Discussion by applehph** [AlexSim93/pull-request-analytics-action#23] [General]
Hi Alex,

I recently try to setup a pipeline to generate PR analytics, however I didn't find any report generated as an issue.
I addition, it seems to only scan two repositories of over a hundred repositories under my organisation. 

Do you know why?

Thank you in advance!

BR,
Pinghua Huang

**Comment by AlexSim93** [comment]
Hi, I would recommend to check logs. I have added validations so your workflow might be stopped because some of inputs are incorrect. All errors should be displayed in logs.
It would be great for me to check your inputs(without sensitive information), so it would be easier for me to help you.
To generate report in new issue, you should set EXECUTION_OUTCOME as new-issue(or just skip this input). GITHUB_REPO_FOR_ISSUE, GITHUB_OWNER_FOR_ISSUE are required in your case as well as GITHUB_OWNERS_REPOS or ORGANIZATIONS.
In case you have noticed bug please describe it here or create an issue.
Thanks!

**Reply by applehph** [reply]
HI Alex,

Thanks for your response. The issue mentioned above about no report is resolved after I set EXECUTION_OUTCOME as new-issue. However the report only contains fewer repositories than the organisation has (109). Do you know why it is like that? 
I attached the screen shot of log of analysis step from the pipeline and the screen shot of repos.
<img width="480" alt="image" src="https://github.com/AlexSim93/pull-request-analytics-action/assets/51174936/b1ec010f-7934-44d6-8a8f-bbb27a0dc30b">
<img width="1144" alt="image" src="https://github.com/AlexSim93/pull-request-analytics-action/assets/51174936/e057dbd7-85d8-4f1f-99a0-c9148252c320">
I also copy the code here:

```
name: "Yearly Statistics Update Every Monday"
 #on:
 #  schedule:
 #    - cron: "0 20 * * 0"

 on:
   pull_request:
     types:
       - opened
       - reopened
       - synchronize
     branches:
      # This will trigger on any pullrequest towards master
     - 'master'
 jobs:
   create-report:
     name: "Create report"
     runs-on: ubuntu-latest
     steps:
       - name: "Runs script for analytics"
         uses: AlexSim93/pull-request-analytics-action@master
         with:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
           LABELS: "Report"
           ORGANIZATIONS: "C4IROcean"
           GITHUB_OWNER_FOR_ISSUE: "C4IROcean"
           GITHUB_REPO_FOR_ISSUE: "app-odcat"
           CORE_HOURS_START: "9:00"
           CORE_HOURS_END: "19:00"
           TIMEZONE: "Europe/Berlin"
           REPORT_DATE_START: 01/01/2023
           # REPORT_PERIOD: "months:3"
           AGGREGATE_VALUE_METHODS: average
           SHOW_STATS_TYPES: timeline
           PERIOD_SPLIT_UNIT: none
           EXECUTION_OUTCOME: new-issue
           ISSUE_NUMBER: 1
```

Thank you in advance!

BR,
Pinghua
