### ISSUE TITLE
Something wrong with report

### ISSUE THREAD

**Issue by TheMY3** [AlexSim93/pull-request-analytics-action#33]
Reports works fine, but for now I got error:
```
Data successfully retrieved. Starting report calculations.
/home/runner/work/_actions/AlexSim93/pull-request-analytics-action/master/build/index.js:1345
                collection[userLogin][key].commentsConducted =
                                     ^

TypeError: Cannot read properties of undefined (reading 'total')
    at /home/runner/work/_actions/AlexSim93/pull-request-analytics-action/master/build/index.js:1345:38
    at Array.forEach (<anonymous>)
    at /home/runner/work/_actions/AlexSim93/pull-request-analytics-action/master/build/index.js:1342:26
    at Array.forEach (<anonymous>)
    at prepareDiscussions (/home/runner/work/_actions/AlexSim93/pull-request-analytics-action/master/build/index.js:1286:24)
    at /home/runner/work/_actions/AlexSim93/pull-request-analytics-action/master/build/index.js:738:40
    at Array.forEach (<anonymous>)
    at collectData (/home/runner/work/_actions/AlexSim93/pull-request-analytics-action/master/build/index.js:713:26)
    at main (/home/runner/work/_actions/AlexSim93/pull-request-analytics-action/master/build/index.js:18[30](...):55)
```
Example of config:
```
name: "PR Analytics"
on:
  workflow_dispatch:
    inputs:
      report_date_start:
        description: "Report date start(d/MM/yyyy)"
        required: false
      report_date_end:
        description: "Report date end(d/MM/yyyy)"
        required: false
jobs:
  create-report:
    name: "Create report"
    runs-on: ubuntu-latest
    steps:
      - name: "Run script for analytics"
        uses: AlexSim93/pull-request-analytics-action@master
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          LABELS: "Report"
          GITHUB_REPO_FOR_ISSUE: "owner"
          GITHUB_OWNER_FOR_ISSUE: "owner"
          GITHUB_OWNERS_REPOS: "owner/owner"
          CORE_HOURS_START: "9:00"
          CORE_HOURS_END: "18:00"
          TIMEZONE: "Europe/Kiev"
          REPORT_DATE_START: ${{ inputs.report_date_start }}
          REPORT_DATE_END: ${{ inputs.report_date_end }}
```
