### ISSUE TITLE
Cannot read properties of null (reading 'login'): '`review.user` is null' problem

### ISSUE THREAD

**Issue by vergil-zhao** [AlexSim93/pull-request-analytics-action#35]
**Describe the bug**
I tried to fetch all PRs in the repo to generate the report, then it returned errors like below. Not sure which PR made this error, a guess is that the deleted user (ghost) created PR may be the culprit like in #5.

**Expected behavior**

**Configuration**
```yaml
name: PR Analytics
on:
  workflow_dispatch:
    inputs:
      report_date_start:
        description: "Report date start(d/MM/yyyy)"
        required: false
      report_date_end:
        description: "Report date end(d/MM/yyyy)"
        required: false

jobs:
  create-report:
    name: "Create report"
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read
      issues: write
    steps:
      - name: "Run script for analytics"
        uses: AlexSim93/pull-request-analytics-action@v2
        with:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
          GITHUB_REPO_FOR_ISSUE: "***"
          GITHUB_OWNER_FOR_ISSUE: "***"
          GITHUB_OWNERS_REPOS: "***/***"
          CORE_HOURS_START: "9:00"
          CORE_HOURS_END: "18:00"
          TIMEZONE: "Asia/Shanghai"
          REPORT_DATE_START: ${{ inputs.report_date_start }}
          REPORT_DATE_END: ${{ inputs.report_date_end }}
```

**Screenshots**
<img width="958" alt="PR_Analytics_·_Zennioptical_customer-data-platform_7ecbc3a" src="https://github.com/AlexSim93/pull-request-analytics-action/assets/4736661/3f55de05-6563-4f18-a679-e78d300113fc">
