### ISSUE TITLE
At most 100 PRs were used even with `AMOUNT: 10000` and `REPORT_PERIOD: 'weeks:4'`

### ISSUE THREAD

**Issue by gavinliukaiber** [AlexSim93/pull-request-analytics-action#40]
Hi :) 
**Describe the bug**
At most 100 PRs were used even with `AMOUNT: 10000` and `REPORT_PERIOD: 'weeks:4'`

**Expected behavior**
The report should include all the PRs in the last 4 weeks. And this is my intention.

**Configuration**

This is how i am calling the action:
```
    steps:
      - name: 'PR Analytics for last 4 weeks'
        uses: AlexSim93/pull-request-analytics-action@v2
        with:
          REPORT_PERIOD: 'weeks:4'
          ISSUE_TITLE: 'Weekly Analytics for Last Month'
          AMOUNT: 10000
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPO_FOR_ISSUE: 'a'
          GITHUB_OWNER_FOR_ISSUE: 'a'
          ORGANIZATIONS: 'a'
          CORE_HOURS_START: '9:00'
          CORE_HOURS_END: '19:00'
          TIMEZONE: 'America/Los_Angeles'
          PERIOD_SPLIT_UNIT: 'none' # Avoid generating additional reports which splits the period
```

**Logs**

This is the log: 
<img width="452" alt="image" src="https://github.com/AlexSim93/pull-request-analytics-action/assets/141545542/88bf30f1-0a25-4789-86f5-bab33ff74b56">

**Screenshots**

This is the report showing only the last 100 PR was used:
<img width="358" alt="image" src="https://github.com/AlexSim93/pull-request-analytics-action/assets/141545542/6bc57822-e94e-45ba-99c5-667e9b0c814e">
<img width="95" alt="image" src="https://github.com/AlexSim93/pull-request-analytics-action/assets/141545542/400d71d7-fd0e-49b7-b881-e61a90d46c62">

**Additional context**
