### ISSUE TITLE
Missing authorization header on GET pull requests

### ISSUE THREAD

**Issue by blo-dawn** [AlexSim93/pull-request-analytics-action#64]
**Describe the bug**
The call to get repos pulls is failing with a 404 Not Found error from GitHub API

**Expected behavior**
Receive a list of Pull Requests

**Configuration**
It is an organization private repo, workflow was setup as:

```
name: "PR Analytics"
on:
  workflow_dispatch:
    inputs:
      report_date_start:
        description: "Report date start(d/MM/yyyy)"
      report_date_end:
        description: "Report date end(d/MM/yyyy)"
jobs:
  create-report:
    name: "Create report"
    runs-on: ubuntu-latest
    steps:
      - name: "Run script for analytics"
        uses: AlexSim93/pull-request-analytics-action@v4
        with:
          GITHUB_TOKEN: ${{ secrets.BLO_PERSONAL_TOKEN }} # In the case of a personal access token, it needs to be added to the repository's secrets and used in this field.
          GITHUB_REPO_FOR_ISSUE: "DawnHealthGit/kisqali-backend" # Make sure to specify the name of the repository where the issue will be created
          GITHUB_OWNER_FOR_ISSUE: "DawnHealthGit" # Make sure to specify the owner of the repository where the issue will be created
          GITHUB_OWNERS_REPOS: "DawnHealthGit/kisqali-backend" # Be sure to list the owner and repository name in the format owner/repo
          CORE_HOURS_START: "9:00"
          CORE_HOURS_END: "19:00"
          TIMEZONE: "Europe/Berlin"
          REPORT_DATE_START: ${{ inputs.report_date_start }}
          REPORT_DATE_END: ${{ inputs.report_date_end }}
```

where `secrets.BLO_PERSONAL_TOKEN` is my own private token created with `repo` and `read:org`

**Logs**
```
Run AlexSim93/pull-request-analytics-action@v4
  with:
    GITHUB_REPO_FOR_ISSUE: DawnHealthGit/kisqali-backend
    GITHUB_OWNER_FOR_ISSUE: DawnHealthGit
    GITHUB_OWNERS_REPOS: DawnHealthGit/kisqali-backend
    CORE_HOURS_START: 9:00
    CORE_HOURS_END: 19:00
    TIMEZONE: Europe/Berlin
    REPORT_DATE_START: 1/01/2025
    REPORT_DATE_END: 26/03/2025
    SHOW_STATS_TYPES: timeline, workload, pr-quality, code-review-engagement, response-time
    AMOUNT: 100
    WEEKENDS: 0,6
    PERCENTILE: 75
    TOP_LIST_AMOUNT: 5
    PERIOD_SPLIT_UNIT: months
    AGGREGATE_VALUE_METHODS: percentile
    EXECUTION_OUTCOME: new-issue
    ALLOW_ANALYTICS: true
    USE_CHARTS: false
    SHOW_CORRELATION_GRAPHS: false
    SHOW_ACTIVITY_TIME_GRAPHS: false
RATE LIMIT REMAINING BEFORE REQUESTS:  60
Initiating data request.
Error while fetching teams: HttpError: Requires authentication
node:internal/process/promises:391
    triggerUncaughtException(err, true /* fromPromise */);
    ^

RequestError [HttpError]: Not Found
    at /home/runner/work/_actions/AlexSim93/pull-request-analytics-action/v4/build/index.js:12522:21
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async requestWithGraphqlErrorHandling (/home/runner/work/_actions/AlexSim93/pull-request-analytics-action/v4/build/index.js:11993:20)
    at async Job.doExecute (/home/runner/work/_actions/AlexSim93/pull-request-analytics-action/v4/build/index.js:14275:18) {
  status: 404,
  response: {
    url: 'https://api.github.com/repos/DawnHealthGit/kisqali-backend/pulls?per_page=100&page=1&state=closed&sort=updated&direction=desc',
    status: 404,
    headers: {
      'access-control-allow-origin': '*',
      'access-control-expose-headers': 'ETag, Link, Location, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Used, X-RateLimit-Resource, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval, X-GitHub-Media-Type, X-GitHub-SSO, X-GitHub-Request-Id, Deprecation, Sunset',
      'content-encoding': 'gzip',
      'content-length': '123',
      'content-security-policy': "default-src 'none'",
      'content-type': 'application/json; charset=utf-8',
      date: 'Wed, 26 Mar 2025 16:02:14 GMT',
      'referrer-policy': 'origin-when-cross-origin, strict-origin-when-cross-origin',
      server: 'github.com',
      'strict-transport-security': 'max-age=31536000; includeSubdomains; preload',
      vary: 'Accept-Encoding, Accept, X-Requested-With',
      'x-content-type-options': 'nosniff',
      'x-frame-options': 'deny',
      'x-github-api-version-selected': '2022-11-28',
      'x-github-media-type': 'github.v3; format=json',
      'x-github-request-id': '1081:269E20:3066013:320D3CE:67E42505',
      'x-ratelimit-limit': '60',
      'x-ratelimit-remaining': '58',
      'x-ratelimit-reset': '1743008533',
      'x-ratelimit-resource': 'core',
      'x-ratelimit-used': '2',
      'x-xss-protection': '0'
    },
    data: {
      message: 'Not Found',
      documentation_url: 'https://docs.github.com/rest/pulls/pulls#list-pull-requests',
      status: '404'
    }
  },
  request: {
    method: 'GET',
    url: 'https://api.github.com/repos/DawnHealthGit/kisqali-backend/pulls?per_page=100&page=1&state=closed&sort=updated&direction=desc',
    headers: {
      accept: 'application/vnd.github.v3+json',
      'user-agent': 'octokit.js/3.1.2 octokit-core.js/5.0.2 Node.js/20.19.0 (linux; x64)',
      'x-github-api-version': '2022-11-28'
    },
    request: { hook: [Function: bound bound register], retryCount: 1 }
  }
}

Node.js v20.19.0
```

**Additional context**
From the GET method above, it seems that the **authorization header** is missing, I've manually called with the extra header and I was able to receive the list of pull requests

I've used

```
@HOST = https://api.github.com
@TOKEN = ghp_V7xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx


GET {{HOST}}/repos/DawnHealthGit/kisqali-backend/pulls?per_page=100&page=1&state=closed&sort=updated&direction=desc
authorization: Bearer {{TOKEN}}
accept: application/vnd.github.v3+json
user-agent: "octokit.js/3.1.2 octokit-core.js/5.0.2 Node.js/20.19.0 (linux; x64)"
x-github-api-version: 2022-11-28
```

and I do get the right output from the GitHub API:

<img width="370" alt="Image" src="https://github.com/user-attachments/assets/f2ef57d7-7741-4d7e-a930-84d12c3b06ea" />
